export interface ProviderItem {
  _id: string,
  code?: string | number,
  name: string,
	checkName: string,
  address: string,
  nit: string,
  phone: string,
  email: string,
  creditDays: number,
  credit: number,
  balance: number,
	iva: boolean,
	isr: boolean,
  isExpenses: boolean,
}
